services:
  - type: web
    name: nodelogin-backend
    runtime: node
    rootDir: backend
    plan: starter
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 4000
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
